name: VaroPlugin
version: '1.5'
main: de.vmoon.varoPlugin.VaroPlugin
api-version: '1.20'
commands:
  register:
    description: Registriere dich für das Varo-Plugin
    usage: /register
    permission: varo.register
    permission-message: "Du hast keine Berechtigung, diesen Befehl auszuführen."
  unregister:
    description: Melde einen Spieler ab
    usage: /unregister
permissions:
  varo.register:
    description: Ermöglicht es Spielern, sich zu registrieren
    default: true
